### ISSUE TITLE
GHL integration

### ISSUE THREAD

**Issue by buzzfair** [Superflows-AI/superflows#122]
Wondering whether I can use Superflows with my Saas-over-GHL product. Possible? Please advise!

**Comment by Henry-Pulver** [comment]
Just to clarify: GHL is GoHigherLevel?

If so, we've spoken to them directly and have a working demo version that connects to GHL, so I'd be happy to help set this up for you!

I think it'd be easiest to discuss over a call. Does that work for you? [Here's my calendar](https://calendly.com/henry_pulver/15-min-chat) or we can organise over [email](mailto:henry@superflows.ai)

**Comment by buzzfair** [comment]
Good to hear from you. Thanks for getting back to me about my GoHighLevel
integration question. Please send any info you have via email and I'll also
book a call with you as soon as I can. Talk soon.

~Guin

**Comment by Henry-Pulver** [comment]
Hey, don't think I have your email address (just checked all my folders for an email!) so replying here - looking forward to chatting when you book in! :)
