### ISSUE TITLE
docker-compse up -d

### ISSUE THREAD

**Issue by av8dtop** [Superflows-AI/superflows#174]
superflows log
Applying migration 20231015163802_add-embedded-docs-table.sql...

unexpected EOF

At statement 0: alter table "public"."organizations"

add column "chat_to_docs_enabled" boolean not null default false

Try rerunning the command with --debug to troubleshoot the error.

**Comment by Henry-Pulver** [comment]
Apologies for the slow reply :sweat_smile: 

I can't seem to replicate this locally. Is this the output when running with `--debug` flag set?

**Comment by Henry-Pulver** [comment]
@av8dtop you may have missed my previous message :sweat_smile: 

What operating system are you running on?

**Comment by Henry-Pulver** [comment]
@av8dtop will close this issue by the end of this week unless you get back to me since I can't repro it :shrug:
